FROM node:10.16.3
WORKDIR /back-end
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
COPY ./package*.json ./
RUN npm install && npm install mocha -g
COPY ./ ./
RUN echo ls
CMD /wait && mocha test/test.js --exit